# Generated by Django 2.2.4 on 2020-01-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20200124_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
